package com.ericzumba.commons;

import org.junit.Before;
import org.junit.Test;

import java.util.HashMap;
import java.util.concurrent.ConcurrentHashMap;

import static java.lang.Integer.valueOf;
import static java.lang.System.currentTimeMillis;
import static org.junit.Assert.*;
import static java.lang.String.format;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ericzumba' at '11/10/16 12:13 AM' with Gradle 3.1
 *
 * @author ericzumba, @date 11/10/16 12:13 AM
 */
public class ChooserTest {

    private Chooser<String, Integer> c;

    @Before
    public void setUp() throws Exception {
        c = new Chooser<>(new HashMap<>(), ques -> -1, ques -> 1);
        c.installRule((answ) -> (answ < 0) ? c.choices(1) : c.choices(0));
    }

    @Test
    public void alwaysStartsByUsingTheFirstChoice() {
        String question = "irrelevant";
        assertEquals(valueOf(-1), c.choose(question));
    }

    @Test
    public void choosesWiselyAfterFirstTime() throws Exception {
        String question = "irrelevant";
        assertEquals(valueOf(-1), c.choose(question));
        assertEquals(valueOf(1), c.choose(question));
        assertEquals(valueOf(-1), c.choose(question));
        assertEquals(valueOf(1), c.choose(question));
    }
}
