package com.ericzumba.commons;

import java.util.function.Function;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ericzumba' at '11/10/16 12:13 AM' with Gradle 3.1
 *
 * @author ericzumba, @date 11/10/16 12:13 AM
 */
public class Chooser<T, R> {
    public final Function<T, R> firstChoice;
    public final Function<T, R> alternative;

    public Chooser(Function<T, R> firstChoice, Function<T, R> alternative) {
        this.firstChoice = firstChoice;
        this.alternative = alternative;
    }

    public Chooser<T, R> rule(Function<R, Function<T, R>> rule) {
        return this;
    }

    public R choose(T t) {
        if(!shouldAlternative(t))
            return register(t, firstChoice.apply(t));
        return register(t, alternative.apply(t));
    }

    private R register(T t, R r) {
        return r;
    }

    private boolean shouldAlternative(T t) {
        return false;
    }
}
